name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Check all template data was replaced
        if: ${{ github.repository != 'teamdigitale/gatsby-site' }}
        run: grep CHANGE[M]E -r . && (echo "Replace all occurrences with values relevant to this site"; exit 1) || exit 0

      - run: yarn install --frozen-lockfile
      - run: yarn clean
      - run: yarn build
      - run: yarn pa11y
      - run: yarn html-proofer
      - run: yarn lint
      
      - name: spid-sp-test
        run: |
          sudo apt update && sudo apt install xmlsec1
          pip install spid-sp-test>=0.9.2
          spid_sp_test --metadata-url file://$GITHUB_WORKSPACE/static/saml2/metadata.xml --extra --debug ERROR
